from fts.topology import BOUNDARY_BOTTOM, BOUNDARY_LEFT, BOUNDARY_RIGHT, BOUNDARY_TOP, OPPOSITE_BOUNDARY


def test_opposite_boundary_mapping():
    assert OPPOSITE_BOUNDARY[BOUNDARY_TOP] == BOUNDARY_BOTTOM
    assert OPPOSITE_BOUNDARY[BOUNDARY_BOTTOM] == BOUNDARY_TOP
    assert OPPOSITE_BOUNDARY[BOUNDARY_LEFT] == BOUNDARY_RIGHT
    assert OPPOSITE_BOUNDARY[BOUNDARY_RIGHT] == BOUNDARY_LEFT
